name: hbs
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - pandas=1.5.2=py310h1128e8f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - requests=2.28.1=py310h06a4308_0
  - sqlalchemy=1.4.39=py310h5eee18b_0
  - pip=22.3.1=py310h06a4308_0
  - pip:
      - matplotlib==3.7.1
      - mysql-connector-python==8.0.33
      - mysqlclient==2.1.1
      - seaborn==0.12.2
      
